## Recommendation System Using Correlation

### Dataset Preparation

In [1]:
import pandas as pd

anime = pd.read_csv('anime.csv')

### Exploring the data

In [2]:
anime.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

### Clean the data

In [3]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [4]:
anime.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [5]:
# Here we able to see the null values, need to handle it properly

In [2]:
anime['genre'] = anime['genre'].fillna('Unknown') # Filled genre missed value as Unknown

In [3]:
anime['type'] = anime['type'].fillna('Unknown') # Filled type missed value as Unknown

In [4]:
anime['rating'] = anime['rating'].fillna(anime['rating'].median()) # Filled rating with the median value of rating

In [5]:
anime['episodes'] = pd.to_numeric(anime['episodes'], errors='coerce').fillna(0) # Chaning the episode datatype from object into the numeric value

In [6]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12294 non-null  object
 3   type      12294 non-null  object
 4   episodes  12294 non-null  float64
 5   rating    12294 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(2), int64(2), object(3)
memory usage: 672.5+ KB

In [9]:
anime.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

#### After handling all the missing values, we are not able to see any missing data

In [10]:
anime.describe()

           anime_id      episodes        rating       members
count  12294.000000  12294.000000  12294.000000  1.229400e+04
mean   14058.221653     12.040101      6.475700  1.807134e+04
std    11455.294701     46.257299      1.017179  5.482068e+04
min        1.000000      0.000000      1.670000  5.000000e+00
25%     3484.250000      1.000000      5.900000  2.250000e+02
50%    10260.500000      2.000000      6.570000  1.550000e+03
75%    24794.500000     12.000000      7.170000  9.437000e+03
max    34527.000000   1818.000000     10.000000  1.013917e+06

In [7]:
ratings = pd.read_csv('rating.csv')

In [8]:
ratings.head()

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [9]:
ratings = ratings[ratings.rating != -1]

In [10]:
ratings.head()

     user_id  anime_id  rating
47         1      8074      10
81         1     11617      10
83         1     11757      10
101        1     15451      10
153        2     11771      10

In [11]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6337241 entries, 47 to 7813736
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 193.4 MB

In [12]:
ratings.isnull().sum()

user_id     0
anime_id    0
rating      0
dtype: int64

In [52]:
# Merging the anime and rating to make a new dataframe
df = pd.merge(ratings, anime[['anime_id', 'name']], left_on='anime_id', right_on='anime_id')

In [14]:
df.head(20)

,user_id,anime_id,rating,name
0,1,8074,10,Highschool of the Dead
1,1,11617,10,High School DxD
2,1,11757,10,Sword Art Online
3,1,15451,10,High School DxD New
4,2,11771,10,Kuroko no Basket
5,3,20,8,Naruto
6,3,154,6,Shaman King
7,3,170,9,Slam Dunk
8,3,199,10,Sen to Chihiro no Kamikakushi
9,3,225,9,Dragon Ball GT
10,3,341,6,Spiral: Suiri no Kizuna
11,3,430,7,Fullmetal Alchemist: The Conqueror of Shamballa
12,3,527,7,Pokemon
13,3,552,7,Digimon Adventure
14,3,813,10,Dragon Ball Z
15,3,1119,7,Pokemon: Celebi Toki wo Koeta Deai
16,3,1121,7,Pokemon Advanced Generation: Nanayo no Negaibo...
17,3,1122,7,Pokemon Advanced Generation: Rekkuu no Houmons...
18,3,1132,8,Digimon Frontier
19,3,1292,6,Afro Samurai

### Recommedation

In [82]:
# Making pivot table to map the anime ID and user ID appropriately

recommend = df.pivot_table(index='user_id', columns='anime_id', values='rating')

In [16]:
recommend.head()

anime_id,1,5,6,7,8,15,16,17,18,19,...,34238,34239,34240,34252,34283,34324,34325,34349,34367,34475
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,8.0,NaN,NaN,6.0,NaN,6.0,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
"""
    Using this function we are finding the correlation of one anime with another

    Args: df --> DataFrame, anime_id --> Based on the anime_id the user watch will be providing the suggestion

    Return: Top 5 anime suggestion
"""
def SuggestionOfAnime(df, anime_id):
    if anime_id not in df.columns:
        return f"Data not found for this Anime ID: {anime_id}"
    similar_anime = df.corrwith(df[anime_id], axis=0)
    similar_anime = pd.DataFrame(similar_anime, columns=['Correlation'])
    similar_anime.dropna(inplace=True)
    similar_anime = similar_anime.sort_values(by='Correlation', ascending=False)
    return similar_anime.head()

In [76]:
# Using the recommendation function, fetch the related animes for the 19th anime to recommend to the user who has watched this anime.

similar_animes_19 = SuggestionOfAnime(recommend, 19)
print(similar_animes)

C:\Users\Divya S\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py:2999: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\Divya S\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py:3000: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
C:\Users\Divya S\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py:2991: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\Divya S\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
C:\Users\Divya S\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

          Correlation
anime_id
8995              1.0
111               1.0
142               1.0
32174             1.0
34238             1.0

In [77]:
# Another sample for the anime ID 342338

similar_animes_34238 = find_corr(recommend, 34238)
print(similar_animes.head())

C:\Users\Divya S\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py:2991: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\Divya S\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
C:\Users\Divya S\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py:2848: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
C:\Users\Divya S\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py:2999: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\Divya S\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py:3000: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

          Correlation
anime_id
8995              1.0
111               1.0
142               1.0
32174             1.0
34238             1.0

In [81]:
""" 
    Getting the name of the anime based on the anime list

    Args -> Similar_Anime - DAtaframe which have similar anime ID

    Return -> Getting the Anime name.
"""
def GetNameOfTheAnime(similar_animes):
    anime_ids = similar_animes.index.tolist()
    for i in anime_ids:
        anime_name = anime.loc[anime['anime_id'] == i, 'name'].values[0]
        print(anime_name)

In [78]:
GetNameOfTheAnime(similar_animes_19)

Wish Me Mell
Ginga Patrol PJ
Thermae Romae x LOFT Collaboration
Thermae Romae x Asahi Shimbun Digital Collaboration
Badaui Jeonseol Jangbogo

In [80]:
GetNameOfTheAnime(similar_animes_34238)

Tales of Symphonia The Animation: Sekai Tougou-hen
Corrector Yui
Kamikaze Kaitou Jeanne
The iDOLM@STER Cinderella Girls: Anytime, Anywhere with Cinderella.
Osomatsu-san: Ouma de Kobanashi